### ISSUE TITLE
UX of feedback screen.

### ISSUE THREAD

**Issue by lhunath** [appswithlove/updraft-sdk-ios#8]
This screen looks very poor.

1. The white "type of feedback" box looks very out of place on the black transparent shade.  Why is this component using inverted colours instead of the light-text-on-dark that the rest of the UI is using?  Or maybe a design needs to accomodate for a large white-background panel that doesn't look out of place.
2. The bottom buttons are floating in the middle of the screen.
3. The email field is difficult to fill out, with autocorrection on, no email/contact autofill suggestions.

![image](https://user-images.githubusercontent.com/36948/99883141-6535bd00-2bf3-11eb-8f2b-780448bc5f6c.png)

**Comment by raphschwander** [comment]
Thanks @lhunath for your feedback, taking time to write it and suggesting solutions (especially the autofill one), it's greatly appreciated 🚀!
